"""Setup for the Agency Plugin for Claude Code.

This is the "in setup" that maps the harness-in-harness MICRO-skills (the engine's
capability verbs) into MACRO-skills (the capabilities themselves) behind a single
`help` discovery surface. It is SELF-HOSTED: the manifest, the `help` skill, and
the `/agency:help` command are all generated by DOGFOODING the plugin-development
capability (`plugin.scaffold` / `author_skill` / `author_command`) over the live
registry — the engine authors its own Claude Code plugin.

    python -m agency.install [root]   # write the install under `root`
"""
from __future__ import annotations

import os
import sys

from .capabilities.plugin import author_command, author_skill, help_map, scaffold
from .engine import Engine

NAME = "agency"
VERSION = "0.1.0"
DESCRIPTION = ("Harness-in-harness agency engine: code-mode capabilities "
               "(macroskills) over one provenance graph.")
HELP_DESC = ("Use when you need to discover the agency engine's capabilities "
             "(macroskills) and their verbs (the micro-skills).")
CMD_DESC = "Use when you want to list the agency capabilities and their verbs."
CMD_BODY = (
    "Map the agency engine's capabilities (macroskills) to their verbs "
    "(micro-skills) by running the engine's code-mode contract:\n\n"
    "    python -m agency.cli --db agency.db execute --code "
    "'return await call_tool(\"capability_plugin_help\", {\"intent_id\": INTENT})'\n"
)


def generate(engine: Engine) -> dict[str, str]:
    """Produce the install files from the LIVE registry (so `help` always reflects
    the real capability set). Returns {relative_path: file_contents}."""
    reg = engine.registry
    caps = {n: list(reg.get(n).verbs) for n in reg.names()}
    help_doc = help_map(caps)["result"]["doc"]
    return {
        ".claude-plugin/plugin.json": scaffold(NAME, VERSION, DESCRIPTION)["result"],
        "skills/help/SKILL.md": author_skill("help", HELP_DESC, help_doc)["result"],
        "commands/help.md": author_command("help", CMD_DESC, CMD_BODY)["result"],
    }


def write(root: str) -> list[str]:
    engine = Engine(":memory:")
    try:
        files = generate(engine)
    finally:
        engine.memory.close()
    written = []
    for rel, content in files.items():
        path = os.path.join(root, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(content)
        written.append(path)
    return written


if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    for p in write(target):
        print(p)
